/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv8L7LCeg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv8L7LCeg= >>
// ----------- >>
public class AssociationClass1 {
// ----------- << class.extras@AAAAAAF+TxLv8L7LCeg= >>
// ----------- >>
}