/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv8L7eKRk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv8L7eKRk= >>
// ----------- >>
public class Class1 {
    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7WjUQ= >>
    // ----------- >>
    private Prenotazione ;

    public Prenotazione get() {
        return ;
    }

    public void set(Prenotazione ) {
        this. = ;
    }

    public void link(Prenotazione _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF+TxLv8L7eKRk= >>
// ----------- >>
}