/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv77589hg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv77589hg= >>
// ----------- >>
public class Cliente {
    // ----------- << attribute.annotations@AAAAAAF+TxLv776IZ+I= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776JLmw= >>
    // ----------- >>
    private String Cognome;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776KdrQ= >>
    // ----------- >>
    private int IDCliente;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776L77c= >>
    // ----------- >>
    private enum Sesso;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776HTaU= >>
    // ----------- >>
    private Set<Prenotazione>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7TQqU= >>
    // ----------- >>
    private Set<Negozio>  = new HashSet<>();

    private String getNome() {
        return Nome;
    }

    private String getCognome() {
        return Cognome;
    }

    public int getIDCliente() {
        return IDCliente;
    }

    public enum getSesso() {
        return Sesso;
    }

    public Set<Prenotazione> get() {
        return ;
    }

    public Set<Negozio> get() {
        return ;
    }

    private void setNome(String Nome) {
        this.Nome = Nome;
    }

    private void setCognome(String Cognome) {
        this.Cognome = Cognome;
    }

    public void setIDCliente(int IDCliente) {
        this.IDCliente = IDCliente;
    }

    public void setSesso(enum Sesso) {
        this.Sesso = Sesso;
    }

    public void link(Prenotazione _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Negozio _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink(Prenotazione _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Prenotazione _, Iterator<Prenotazione> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink(Negozio _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Negozio _, Iterator<Negozio> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    // ----------- << method.annotations@AAAAAAF+TxLv776MuCY= >>
    // ----------- >>
    public void void Leggi() {
    // ----------- << method.body@AAAAAAF+TxLv776MuCY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+TxLv77589hg= >>
// ----------- >>
}