/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;

// ----------- << imports@AAAAAAF+TxLv776R2rE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv776R2rE= >>
// ----------- >>
public class Listino {
    // ----------- << attribute.annotations@AAAAAAF+TxLv776YT6w= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776ZEkM= >>
    // ----------- >>
    private int ID;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776UTMQ= >>
    // ----------- >>
    private Negozio ;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776Xfj0= >>
    // ----------- >>
    private Negozio ;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776tZoc= >>
    // ----------- >>
    private Taglio ;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776wJas= >>
    // ----------- >>
    private Set<Taglio>  = new HashSet<>();

    public String getNome() {
        return Nome;
    }

    public int getID() {
        return ID;
    }

    public Negozio get() {
        return ;
    }

    public Negozio get() {
        return ;
    }

    public Taglio get() {
        return ;
    }

    public Set<Taglio> get() {
        return ;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public void set(Negozio ) {
        this. = ;
    }

    public void set(Negozio ) {
        this. = ;
    }

    public void set(Taglio ) {
        this. = ;
    }

    public void link(Negozio _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Negozio _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Taglio _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Taglio _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Taglio _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Taglio _, Iterator<Taglio> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF+TxLv776R2rE= >>
// ----------- >>
}