/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv8L7FK8o= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv8L7FK8o= >>
// ----------- >>
public class Macchinario {
    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7Ju7c= >>
    // ----------- >>
    private int IdMacchinario;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7KP14= >>
    // ----------- >>
    private int Ammortamento;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7IwX8= >>
    // ----------- >>
    private Set<Strutturato>  = new HashSet<>();

    public int getIdMacchinario() {
        return IdMacchinario;
    }

    public int getAmmortamento() {
        return Ammortamento;
    }

    public Set<Strutturato> get() {
        return ;
    }

    public void setIdMacchinario(int IdMacchinario) {
        this.IdMacchinario = IdMacchinario;
    }

    public void setAmmortamento(int Ammortamento) {
        this.Ammortamento = Ammortamento;
    }

    public void link(Strutturato _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink(Strutturato _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Strutturato _, Iterator<Strutturato> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF+TxLv8L7FK8o= >>
// ----------- >>
}