/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv776lBHs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv776lBHs= >>
// ----------- >>
public class Negozio {
    // ----------- << attribute.annotations@AAAAAAF+TxLv776mbr8= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776nOHQ= >>
    // ----------- >>
    private int Partita IVA;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776oT8k= >>
    // ----------- >>
    private String Via;

    // ----------- << attribute.annotations@AAAAAAF+T/bFDGpqeAQ= >>
    // ----------- >>
    private int Stelle;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776T2GI= >>
    // ----------- >>
    private Listino ;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776Wy1M= >>
    // ----------- >>
    private Listino ;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L66cnk= >>
    // ----------- >>
    private Prenotazione ;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7SW0E= >>
    // ----------- >>
    private Set<Cliente>  = new HashSet<>();

    public String getNome() {
        return Nome;
    }

    public int getPartita IVA() {
        return Partita IVA;
    }

    public String getVia() {
        return Via;
    }

    public int getStelle() {
        return Stelle;
    }

    public Listino get() {
        return ;
    }

    public Listino get() {
        return ;
    }

    public Prenotazione get() {
        return ;
    }

    public Set<Cliente> get() {
        return ;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public void setPartita IVA(int Partita IVA) {
        this.Partita IVA = Partita IVA;
    }

    public void setVia(String Via) {
        this.Via = Via;
    }

    public void setStelle(int Stelle) {
        this.Stelle = Stelle;
    }

    public void set(Listino ) {
        this. = ;
    }

    public void set(Listino ) {
        this. = ;
    }

    public void set(Prenotazione ) {
        this. = ;
    }

    public void link(Listino _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Listino _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Prenotazione _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cliente _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Cliente _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Cliente _, Iterator<Cliente> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    // ----------- << method.annotations@AAAAAAF+TxLv776pDZ0= >>
    // ----------- >>
    public void void RimuoviPrenotazione() {
    // ----------- << method.body@AAAAAAF+TxLv776pDZ0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF+TxLv776qp2w= >>
    // ----------- >>
    public void void leggiPrenotazione() {
    // ----------- << method.body@AAAAAAF+TxLv776qp2w= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+TxLv776lBHs= >>
// ----------- >>
}