/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv8L7Qqak= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv8L7Qqak= >>
// ----------- >>
public class Prenotazione {
    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7YdVE= >>
    // ----------- >>
    private LocalDate Data;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7Z6v0= >>
    // ----------- >>
    private timestamp Ora;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7ar8I= >>
    // ----------- >>
    private String Codice;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7bo9k= >>
    // ----------- >>
    private void Attribute1;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7cyJ8= >>
    // ----------- >>
    private void LeggiParametri;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776Ao1I= >>
    // ----------- >>
    private Strutturato ;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776Ekb0= >>
    // ----------- >>
    private Semplice ;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7XAs4= >>
    // ----------- >>
    private Class1 ;

    public LocalDate getData() {
        return Data;
    }

    public timestamp getOra() {
        return Ora;
    }

    public String getCodice() {
        return Codice;
    }

    public void getAttribute1() {
        return Attribute1;
    }

    public void getLeggiParametri() {
        return LeggiParametri;
    }

    public Strutturato get() {
        return ;
    }

    public Semplice get() {
        return ;
    }

    public Class1 get() {
        return ;
    }

    public void setData(LocalDate Data) {
        this.Data = Data;
    }

    public void setOra(timestamp Ora) {
        this.Ora = Ora;
    }

    public void setCodice(String Codice) {
        this.Codice = Codice;
    }

    public void setAttribute1(void Attribute1) {
        this.Attribute1 = Attribute1;
    }

    public void setLeggiParametri(void LeggiParametri) {
        this.LeggiParametri = LeggiParametri;
    }

    public void set(Strutturato ) {
        this. = ;
    }

    public void set(Semplice ) {
        this. = ;
    }

    public void set(Class1 ) {
        this. = ;
    }

    public void link(Strutturato _) {
        if (_ != null) {
            _.getSceglie().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Semplice _) {
        if (_ != null) {
            _.getCollegata().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Class1 _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().getSceglie().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().getCollegata().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF+TxLv8L7d9wo= >>
    // ----------- >>
    public void void LeggiParametri() {
    // ----------- << method.body@AAAAAAF+TxLv8L7d9wo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+TxLv8L7Qqak= >>
// ----------- >>
}