/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv8L6/wQY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv8L6/wQY= >>
// ----------- >>
public class Prodotto {
    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7Dm3k= >>
    // ----------- >>
    private int IdProdotto;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7ET4E= >>
    // ----------- >>
    private int Dimensione;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7CBzg= >>
    // ----------- >>
    private Set<Strutturato>  = new HashSet<>();

    public int getIdProdotto() {
        return IdProdotto;
    }

    public int getDimensione() {
        return Dimensione;
    }

    public Set<Strutturato> get() {
        return ;
    }

    public void setIdProdotto(int IdProdotto) {
        this.IdProdotto = IdProdotto;
    }

    public void setDimensione(int Dimensione) {
        this.Dimensione = Dimensione;
    }

    public void link(Strutturato _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink(Strutturato _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Strutturato _, Iterator<Strutturato> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF+TxLv8L6/wQY= >>
// ----------- >>
}