/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv776akzc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv776akzc= >>
// ----------- >>
public class Semplice extends Taglio {
    // ----------- << attribute.annotations@AAAAAAF+TxLv776ch8s= >>
    // ----------- >>
    private void Descrizione;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776drGI= >>
    // ----------- >>
    private void Procedura;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776Dqe8= >>
    // ----------- >>
    private Set<Prenotazione> Collegata = new HashSet<>();

    public void getDescrizione() {
        return Descrizione;
    }

    public void getProcedura() {
        return Procedura;
    }

    public Set<Prenotazione> getCollegata() {
        return Collegata;
    }

    public void setDescrizione(void Descrizione) {
        this.Descrizione = Descrizione;
    }

    public void setProcedura(void Procedura) {
        this.Procedura = Procedura;
    }

    public void linkCollegata(Prenotazione _Collegata) {
        if (_Collegata != null) {
            _Collegata.unlink();
            _Collegata.set(this);
            getCollegata().add(_Collegata);
        }
    }

    public void unlinkCollegata(Prenotazione _Collegata) {
        if (_Collegata != null) {
            _Collegata.set(null);
            getCollegata().remove(_Collegata);
        }
    }

    public void unlinkCollegata(Prenotazione _Collegata, Iterator<Prenotazione> it) {
        if (_Collegata != null) {
            _Collegata.set(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF+TxLv776akzc= >>
// ----------- >>
}