/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv776em7o= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv776em7o= >>
// ----------- >>
public class Strutturato extends Taglio,Taglio {
    // ----------- << attribute.annotations@AAAAAAF+TxLv776hT9o= >>
    // ----------- >>
    private void Descrizione;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776iGFE= >>
    // ----------- >>
    private void Procedura;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776jd10= >>
    // ----------- >>
    private String Macchinari;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776kkkQ= >>
    // ----------- >>
    private String Prodotti;

    // ----------- << attribute.annotations@AAAAAAF+TxLv775/WFU= >>
    // ----------- >>
    private Set<Prenotazione> Sceglie = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7BuqU= >>
    // ----------- >>
    private Set<Prodotto>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7HkK4= >>
    // ----------- >>
    private Set<Macchinario>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L7NoI4= >>
    // ----------- >>
    private Prenotazione ;

    public void getDescrizione() {
        return Descrizione;
    }

    public void getProcedura() {
        return Procedura;
    }

    public String getMacchinari() {
        return Macchinari;
    }

    public String getProdotti() {
        return Prodotti;
    }

    public Set<Prenotazione> getSceglie() {
        return Sceglie;
    }

    public Set<Prodotto> get() {
        return ;
    }

    public Set<Macchinario> get() {
        return ;
    }

    public Prenotazione get() {
        return ;
    }

    public void setDescrizione(void Descrizione) {
        this.Descrizione = Descrizione;
    }

    public void setProcedura(void Procedura) {
        this.Procedura = Procedura;
    }

    public void setMacchinari(String Macchinari) {
        this.Macchinari = Macchinari;
    }

    public void setProdotti(String Prodotti) {
        this.Prodotti = Prodotti;
    }

    public void set(Prenotazione ) {
        this. = ;
    }

    public void linkSceglie(Prenotazione _Sceglie) {
        if (_Sceglie != null) {
            _Sceglie.unlink();
            _Sceglie.set(this);
            getSceglie().add(_Sceglie);
        }
    }

    public void link(Prodotto _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Macchinario _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Prenotazione _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkSceglie(Prenotazione _Sceglie) {
        if (_Sceglie != null) {
            _Sceglie.set(null);
            getSceglie().remove(_Sceglie);
        }
    }

    public void unlinkSceglie(Prenotazione _Sceglie, Iterator<Prenotazione> it) {
        if (_Sceglie != null) {
            _Sceglie.set(null);
            it.remove();
        }
    }

    public void unlink(Prodotto _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Prodotto _, Iterator<Prodotto> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink(Macchinario _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Macchinario _, Iterator<Macchinario> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF+TxLv776em7o= >>
// ----------- >>
}