/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ClassDiagram;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+TxLv776r5zM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+TxLv776r5zM= >>
// ----------- >>
public abstract class Taglio {
    // ----------- << attribute.annotations@AAAAAAF+TxLv8L6yq5Q= >>
    // ----------- >>
    private int ID;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L6z12o= >>
    // ----------- >>
    private String tipologia;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L60VpQ= >>
    // ----------- >>
    private Float Costo;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L61apA= >>
    // ----------- >>
    private Int Durata;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L62N20= >>
    // ----------- >>
    private String Descrizione;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L63Trk= >>
    // ----------- >>
    private String Procedura;

    // ----------- << attribute.annotations@AAAAAAF+TxLv776uYqs= >>
    // ----------- >>
    private Listino ;

    // ----------- << attribute.annotations@AAAAAAF+TxLv8L6x9oI= >>
    // ----------- >>
    private Set<Listino>  = new HashSet<>();

    public int getID() {
        return ID;
    }

    public String getTipologia() {
        return tipologia;
    }

    public Float getCosto() {
        return Costo;
    }

    public Int getDurata() {
        return Durata;
    }

    public String getDescrizione() {
        return Descrizione;
    }

    public String getProcedura() {
        return Procedura;
    }

    public Listino get() {
        return ;
    }

    public Set<Listino> get() {
        return ;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public void setTipologia(String tipologia) {
        this.tipologia = tipologia;
    }

    public void setCosto(Float Costo) {
        this.Costo = Costo;
    }

    public void setDurata(Int Durata) {
        this.Durata = Durata;
    }

    public void setDescrizione(String Descrizione) {
        this.Descrizione = Descrizione;
    }

    public void setProcedura(String Procedura) {
        this.Procedura = Procedura;
    }

    public void set(Listino ) {
        this. = ;
    }

    public void link(Listino _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Listino _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Listino _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Listino _, Iterator<Listino> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF+TxLv776r5zM= >>
// ----------- >>
}